# Generated by Django 4.2.4 on 2023-09-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('addressline1', models.CharField(max_length=150)),
                ('addressline2', models.CharField(max_length=150)),
                ('addressline3', models.CharField(max_length=150)),
                ('pin', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, default='', null=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='CakeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('stack', models.CharField(blank=True, default='In Stock', max_length=50, null=True)),
                ('description', models.TextField()),
                ('baseprice', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('finalprice', models.IntegerField()),
                ('pic1', models.ImageField(blank=True, default='', null=True, upload_to='upload')),
                ('cakeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.caketype')),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.flavour')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.shape')),
            ],
        ),
    ]
