# Generated by Django 4.2.4 on 2023-09-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='name',
            new_name='product',
        ),
    ]
